### ISSUE TITLE
How can I run main.c before I open QQ?

### ISSUE THREAD

**Issue by zehuichen123** [doveccl/QQU#1]
I've already used the method mentioned in your blog on how to prevent QQ message recalling and it worked well. But I find that I need to export `libQQUnrecall.dylib` every time. You gave a way to solve this problem by writing these (main.c in your GitHub):
```c++
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define QPATH "/Applications/QQ.app/Contents/MacOS/"
#define LIBENV "DYLD_INSERT_LIBRARIES"
#define LIBNAME "libQQUnrecall.dylib"
#define HOOK "export " LIBENV "=%s" LIBNAME
#define RUN QPATH "QQ"
#define AND " && "
#define CMD HOOK AND RUN
#define M 1024
char path[M], buff[M];
unsigned long len, i;
int main(int argc, char **argv) {
    strcpy(path, argv[0]);
    len = strlen(path);
    for (i = len - 1; i; i--) {
        if (path[i] == '/')
            break ;
        path[i] = 0;
    }
    sprintf(buff, CMD, path);
    system(buff);
    return 0;
}
```
**My question** is where should I put this file and how can I recompile?(I don't know) to run this file every time I open the QQ without using terminal? Hope you can give me some explanation in details, I am quite confused. Thanx!

**Comment by doveccl** [comment]
README.md updated, please read it
Two ways are available to use these code without terminal

**Comment by zehuichen123** [comment]
thanx~
